### ISSUE TITLE
Missing #include <cstdint> in ClockDelta.h causes build failure with GCC 15

### ISSUE THREAD

**Issue by aneshlya** [dreamworksanimation/openmoonray#230]
## Description

Building OpenMoonRay v3.6.0.1 fails with GCC 15 due to missing `#include <cstdint>` in `ClockDelta.h`. The `uint64_t` type is used without the necessary include.

## Error

```
moonray/moonray_arras/mcrt_dataio/lib/share/util/ClockDelta.h:60:44: error: 'uint64_t' has not been declared
moonray/moonray_arras/mcrt_dataio/lib/share/util/ClockDelta.h:61:44: error: 'uint64_t' has not been declared
moonray/moonray_arras/mcrt_dataio/lib/share/util/ClockDelta.h:62:44: error: 'uint64_t' has not been declared
moonray/moonray_arras/mcrt_dataio/lib/share/util/ClockDelta.cc:125:1: error: no declaration matches 'float mcrt_dataio::ClockDelta::analyzeRoundTripTimeDelta(uint64_t, uint64_t, uint64_t, float&)'
```

## Environment

- GCC 15.2.1 on Arch Linux
- OpenMoonRay v3.6.0.1 (via AUR package)

## Suggested Fix

Add `#include <cstdint>` to `ClockDelta.h`.

## Notes

This worked in v2.40.0.1. The issue was introduced somewhere between v2.40.0.1 and v3.6.0.1.
